albicocco_string = [
    "Stadia chiude?",
    "Che motore grafico usa Fifa?",
    "Kalamaygiò...KALAMAHO! Invited to the gaaaame!",
    "Che chioma fluente!",
    "Vacca Boia!",
    "Chro è un lui o una lei?",
    "Ci sono donne su sto server?",
    "Regola n°1 di Stadia Italia? Non toccatemi Facchinetti",
    "Salutate tutti, sua maestà MikkaVez!",
    "Oh ma i ruoli nuovi? Vogliamo i colori !1!111!!",
    "Albicocche..albicocche ovunque!",
    "Ce nge na ma scì sciamanìnne, ce non ge na ma scì non ge ne sime scènne! - Shaman King",
    "Mei murė sufegá dala brügna che dal biönc - Mysteris",
    "Mi sono appena fermato a un supermercato svizzero a prendere un panino. Ho chiesto un francese con il prosciutto cotto. Mi hanno risposto che il francese in Svizzera non esiste, si chiama birichino…Buon dio. - Enuzzo",
    "Il problema non sono le 3 ragazze su 180.... è l'1 Mikkaels su 180! - Mysteris",
    "Secondo voi Google me lo fa cambiare il Nick di Stadia in albicocco giusto per la partita di sta sera e poi tornare kalamajo oppure mi sputa in faccia? - Kalamajo",
    "3 chiavi dorate, il codice scade domani! - HankJW",
    "Se un designer è anche coder diventa un decoder? - Mikkaels",
    "https://tenor.com/view/shrek-princess-fiona-when-the-caffeine-hits-when-the-dick-too-good-dick-too-good-gif-5611089",
    "Il passato delle persone non ha importanza, solo il presente dice chi siamo. E ora lo so. - Kalamajo",
    "(Riferendosi alla sconfitta su power rangers) Non so se riuscirò a scopare neanche la mia donna stasera! - Kalamajo",
    "NIENTE BESTEMMIE!",
    "Ragazzi benvenuti nella decima live di Kobe con una sola views!",
    "Saluta Kalamajo? Ciao Karamaggio! - Kobe junior",
    "Savage Planet chiude?",
    "Comunque grazie a chi ha creduto che stessi per investire Maria Grazia Cucinotta. Ci ho creduto così tanto che mi sono votato pure io - Chro",
    "Ragazzi dove è finito Pigrotto?",
    "Se mi dessero un vezcoin per ogni stronzata che ho detto..adesso sarei RiccoVez",
    "BY THE POWER OF GRAYSKULL, I HAVE THE POWER!",
    "Se mi aveste scelto, sarei stato sicuramente un Leonida migliore di quello attuale :(",
    "Se per caso il mio smartphone finisce in acqua o subisce altro generi di danni, l'account di Google Stadia e i giochi presenti subbiscono anch'essi qualche danno? - eroe di Stadia Italia" 
]

