albicocco_string = [
    "Stadia chiude?",
    "Che motore grafico usa Fifa?",
    "Kalamaygiò...KALAMAHO! Invited to the gaaaame!",
    "Che chioma fluente!",
    "Vacca Boia!",
    "Chro è un lui o una lei?",
    "Ci sono donne su sto server?",
    "Regola n°1 di Stadia Italia? Non toccatemi Facchinetti",
    "Salutate tutti, sua maestà MikkaVez!",
    "Oh ma i ruoli nuovi? Vogliamo i colori !1!111!!",
    "Albicocche..albicocche ovunque!",
    "Ce nge na ma scì sciamanìnne, ce non ge na ma scì non ge ne sime scènne! - Shaman King",
    "Mei murė sufegá dala brügna che dal biönc - Mysteris",
    "Mi sono appena fermato a un supermercato svizzero a prendere un panino. Ho chiesto un francese con il prosciutto cotto. Mi hanno risposto che il francese in Svizzera non esiste, si chiama birichino…Buon dio. - Enuzzo",
    "Il problema non sono le 3 ragazze su 180.... è l'1 Mikkaels su 180! - Mysteris",
    "Secondo voi Google me lo fa cambiare il Nick di Stadia in albicocco giusto per la partita di sta sera e poi tornare kalamajo oppure mi sputa in faccia? - Kalamajo",
    "3 chiavi dorate, il codice scade domani! - HankJW",
    "Se un designer è anche coder diventa un decoder? - Mikkaels",
    "https://tenor.com/view/shrek-princess-fiona-when-the-caffeine-hits-when-the-dick-too-good-dick-too-good-gif-5611089",
    "Il passato delle persone non ha importanza, solo il presente dice chi siamo. E ora lo so. - Kalamajo",
    "(Riferendosi alla sconfitta su power rangers) Non so se riuscirò a scopare neanche la mia donna stasera! - Kalamajo",
    "NIENTE BESTEMMIE!"
]

